language: generic
sudo: required
services: docker
branches:
  only:
    - master
env:
  global:
    - PROJECT_NAME=lpp-api-gateway
    - PROJECT_VERSION=1.0.1
    - DOCKER_USERNAME=bezpov
    - secure: CBi+UWBxYoqT68fUjpCOgv6f23nzrfC1imVjs/FGCxn2ke5wcEyQVddzLgPnVXA5mNPJqg3pzA3UO7fRXUF3vWLONyf7rzJqa3BbQVqvBYWeHO9LCTehs3FU19e3m0OesCo91Hok41elCHM2V/l7X6NXnuR4lFsFhNZeRa1L6pDMv2PIGe8sWat18LQPDTxaaVCIMSUYur1gFainW3ScfJnOR0oebnbUM6iisOQyLh5wT/vlgULu9JUh+Na0X2tcFu9TrP6zF2MPB9PFBNE9opAjhh3ex7cGLAEXlLL7IaT088moHGurVUk8uISbwJ6LCl835Y3LjZ2AU2zy9lUr/xZp8K7abiSpaGIAkmovg0QZDnpM4WCkL4s0XLL7+Oc3wn85tV+KlTfGvYdgy2ytDlSj2VJ9JsSFE4hFR/O7+Pbcy4sKFGCHHdSRMLrNYNo9ijCiKvHX2XfsVevLFl9Mtj2SaoTT7jnjgrB+y60htZ0uQCSkBVWZCyJhoFPC+OGov6ScO9ZwEudUsCrAmviTrpSbhS4jJQGEtA6Q1DG3eotHSn2KRRPVbvi9rsgg1GnOzxBwQSuKRxA4sIqFDaEBzjvGizclS/lFeJ5NY24VcxhLQE3ncK+twKDR4/XYk1mGzZSBREuCRD5U1/bulqxuXR9dt/sseFvHNxJ3dT5CMQg=
    - secure: Hnj9mBuYSP00OfSckRHbbyP1ueA4FpGIOwf+eXQ5bSgL9mmow3HUyTLZ30OrSQ7gAsMCSXORUuOibwLYjMh6R4SRoLfM4vSije0adMZqXv1Wnh4X4A+bTYBnc7HoqEMQrc1BFcMf+/qGht3mGazAkXoKKuV+XJ221prQLjA+2NbIWb1uTlB36Bs2hLp1katw/3UcNX6SKDC5xDpFO7PCmczNCtdA6oqrJBCnIWtYoA4mSgUwGUqiw/J1e4Y5ekdvPe/IPfhd0pyPV89taq9GVdLJEUdKoiaC59AtAm+W7Sdrm+mZyhyl3P2T3OXI8GfMZJkSIYLZRRpP6hu0336O4qfbn6e0zHrAUhyYi9jYsOI/DcQGNAeNKAeA5TctFE8wdIpAnnbeh3hZpVuNdUYteRw+JrbXmJlp+dR5iyWNiviMyEOGt2gyst/+6UkDp/KQeeO3a2HYVamvdN07RM9I43N+xU7ZDwReptIUaiIiQe79L5dzRZuQr+E104pYQC57blOM7wZNv3/ccD9f8mmK0njxgzbHL3IbxThCaclg9yPCVrFWWyVkSSEPn+lN7eNBC5jPkd1BMEx28ZSQw3Mo27uA/0WI1hzXpL9zarLf8QyXVBF+ULuHvuKiPDO8HH/A+URqVAG170bVCo+Ig3QC7Bv0hRhn7pJACP8uCoJxr7c=
before_install:
  - openssl aes-256-cbc -k "$google-integration-password" -in google-travis-service-account.json.enc -out google-travis-service-account.json -d
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker image build -t $PROJECT_NAME:$PROJECT_VERSION .
  - docker image tag $PROJECT_NAME:$PROJECT_VERSION $DOCKER_USERNAME/$PROJECT_NAME:$PROJECT_VERSION
  - docker image push $DOCKER_USERNAME/$PROJECT_NAME
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
    CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud auth activate-service-account --key-file google-travis-service-account.json
  - gcloud config set project massive-boulder-263710
  - gcloud container clusters get-credentials lpp --zone us-central1-a --project massive-boulder-263710
  - gcloud components install kubectl
  - kubectl apply -f ./kubernetes/deployment.yaml
